version: "2"
networks:
   db-net:
     driver: bridge
   proxy:
     driver: bridge


services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
      container_name: elasticsearch
      restart: always
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=false
        - cluster.routing.allocation.disk.threshold_enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./db/elastic/data:/usr/share/elasticsearch/data
        - ./db/elastic/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      networks:
        - db-net

    kibana:
     image: docker.elastic.co/kibana/kibana:7.6.0
     container_name: kibana
     volumes:
       - ./admin/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
     networks:
       - db-net
       - proxy
     ports:
       - 8444:5601
     environment:
       VIRTUAL_HOST: kibana.${DOMAIN}
       VIRTUAL_PORT: 5601
       LETSENCRYPT_HOST: kibana.${DOMAIN}
       LETSENCRYPT_EMAIL: ${EMAIL}

    micro-extract:
      build: ./Micro-extract/
      container_name: ocr
      tty: true
      stdin_open: true
      restart: always
      ports:
        - 80:8080
      networks:
        - db-net
        - proxy
      environment:
        API_PASS: 1q2W3e4R%T^Y
