version: "2"
networks:
   db-net:
     driver: bridge
   proxy:
     driver: bridge


services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
      container_name: elasticsearch
      restart: always
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=false
        - cluster.routing.allocation.disk.threshold_enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./Db/elastic/data:/usr/share/elasticsearch/data
        - ./Db/elastic/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      networks:
        - db-net

    bck-end:
      build: ./Api/
      container_name: bck-end
      tty: true
      stdin_open: true
      restart: always
      ports:
        - 80:8080
      networks:
        - db-net
        - proxy
      environment:
        API_PASS: 1q2W3e4R%T^Y

    kibana:
      image: docker.elastic.co/kibana/kibana:7.6.0
      container_name: kibana
      volumes:
        - ./Admin/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
        - db-net
        - proxy
      ports:
        - 8444:5601
