version: "3"
networks:
   db-net:
     driver: bridge
   proxy:
     driver: bridge

services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
      container_name: mouseion-es
      restart: always
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=false
        - cluster.routing.allocation.disk.threshold_enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: "65536"
          hard: "65536"
      volumes:
        - ../Mouseion/Db/elastic/data:/usr/share/elasticsearch/data
        - ../Mouseion/Db/elastic/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      networks:
        - db-net
      healthcheck:
       test: "curl -Ls -o /dev/null -w \"%{http_code}\n%{url_effective}\n\" http://localhost:9200/_cat/health"
       interval: 30s
       timeout: 1s
       retries: 1

    bck-end:
      build: ../Mouseion/Webapp/Api/
      container_name: mouseion-bck-end
      tty: true
      stdin_open: true
      restart: always
      ports:
        - 80:8080
      volumes:
        - ../Mouseion/Webapp/Api:/home/root/Api
      networks:
        - db-net
        - proxy
      environment:
        API_PASS: 1q2W3e4R%T^Y
      healthcheck:
       test: "curl -Ls -o /dev/null -w \"%{http_code}\n%{url_effective}\n\" http://localhost:8080"
       interval: 30s
       timeout: 1s
       retries: 1

    kibana:
      image: docker.elastic.co/kibana/kibana:7.6.0
      container_name: mouseion-kibana
      restart: always
      ports:
        - 8080:5601
      volumes:
        - ../Mouseion/Admin/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
        - db-net
        - proxy
      healthcheck:
       test: "curl -Ls -o /dev/null -w \"%{http_code}\n%{url_effective}\n\" http://localhost:5601"
       interval: 30s
       timeout: 1s
       retries: 1
